name: 🚗 [Claim] Deploy Production (main)

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_production:
    uses: ./.github/workflows/webview.build_and_deploy.yml
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    with:
      CLOUDFLARE_PROJECT_NAME: "test-deploy"
      CLOUDFLARE_BRANCH_TARGET: "main"
      PROJECT_TYPE: "claim-web"

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Version Name
        uses: actions/github-script@v6
        id: version
        with:
          result-encoding: string
          script: |
            const timeZoneOffset = 9 * 60 * 60 * 1000;
            const yyyymmddhhmm = new Date(Date.now() + timeZoneOffset).toISOString().replace(/[^0-9]/g, '').slice(0, -5);
            return yyyymmddhhmm;
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: create tag
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git tag -a -f ${{ steps.version.outputs.result }} -m "Release ${{ steps.version.outputs.result }}"
          git push -f origin ${{ steps.version.outputs.result }}
      - name: create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: ${{ steps.version.outputs.result }}
          name: "${{ steps.version.outputs.result }} 배포"
          generateReleaseNotes: true
          omitBodyDuringUpdate: true
